version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: university_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/university_data
      DEBUG: "True"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
