services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: university_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8100:8100"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/university_data
      DEBUG: "True"
      DROP_TABLES: "true"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    entrypoint: ["./entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/docs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
